### ISSUE TITLE
InflateException: Binary XML file line #18: Error inflating class TextView

### ISSUE THREAD

**Issue by drakeet** [RikkaW/MaterialPreference#12]
I get a FATAL EXCEPTION when running the sample in Android 4.4:

```java
android.view.InflateException: Binary XML file line #18: Error inflating class TextView
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
      at moe.shizuku.preference.PreferenceGroupAdapter.onCreateViewHolder(PreferenceGroupAdapter.java:275)
      at moe.shizuku.preference.PreferenceGroupAdapter.onCreateViewHolder(PreferenceGroupAdapter.java:36)
      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6488)
      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5675)
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5558)
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5554)
      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3694)
      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3411)
      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3963)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
     at android.view.ViewRootImpl.perf
```

**Comment by drakeet** [comment]
I found the reason in the source of MaterialPreference:

![image](https://user-images.githubusercontent.com/5214214/29051016-4598526c-7c12-11e7-9349-16a60b0b5738.png)

**Comment by drakeet** [comment]
BTW:
![image](https://user-images.githubusercontent.com/5214214/29051262-cea4399e-7c13-11e7-85b3-c4b74f238643.png)

**Comment by drakeet** [comment]
![image](https://user-images.githubusercontent.com/5214214/29051359-a1881538-7c14-11e7-9f00-5263c2fb727a.png)

**Comment by royCode1** [comment]
I got the same error message not being able to fix it any
 suggestions

**Comment by learningis4fun** [comment]
I removed the TextView and rewritten it. It worked like a charm.
